name: Build, Test, and Deploy Documentation

on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false

      - name: Set up Conda environment
        run: |
          conda init bash
          source ~/.bashrc
          conda create -n ci_env python=3.11 -y
          conda activate ci_env
          pip install --upgrade pip
          pip install pdm==2.20.1 pre-commit coveralls  # Install coveralls here
          pdm config python.use_venv false
          pdm install --dev

      - name: Run pre-commit hooks
        run: |
          source ~/.bashrc
          conda activate ci_env
          pre-commit run -a

      - name: Run tests with coverage
        run: |
          source ~/.bashrc
          conda activate ci_env
          set +e
          pdm run pytest --cov=src --cov-report=term --cov-report=json --cov-report=html --cov-fail-under=85 > coverage_output.txt
          TEST_EXIT_CODE=$?
          set -e
          echo "# Test Coverage Summary" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          grep -A 15 "coverage:" coverage_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat $GITHUB_STEP_SUMMARY
          exit $TEST_EXIT_CODE

      - name: Verify coveralls installation
        run: |
          source ~/.bashrc
          conda activate ci_env
          pip show coveralls

      - name: Upload coverage to Coveralls
        run: |
          source ~/.bashrc
          conda activate ci_env  # Ensure the correct environment is activated before running coveralls
          coveralls --service=github-actions
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
